export const articles = [
  {
    Title: 'Letraset, une société de lettrage française',
    Description:
      'Letraset, une société de lettrage française, a popularisé le passage de Lorem Ipsum dans les années 1960 avec leurs feuilles de transfert à sec.',
    Content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet purus. Id aliquet risus feugiat in. Arcu risus quis varius quam quisque. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Arcu cursus vitae congue mauris. Faucibus interdum posuere lorem ipsum dolor. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Sed turpis tincidunt id aliquet. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Tincidunt vitae semper quis lectus nulla at volutpat. Tempus egestas sed sed risus. Lorem donec massa sapien faucibus et molestie. Ac turpis egestas sed tempus urna et. A arcu cursus vitae congue.\n\nOdio eu feugiat pretium nibh ipsum consequat nisl vel. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Eu mi bibendum neque egestas congue quisque egestas. Quis hendrerit dolor magna eget est lorem ipsum dolor. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Velit scelerisque in dictum non consectetur a erat nam at. Erat nam at lectus urna duis convallis convallis. Amet nisl purus in mollis nunc sed. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Accumsan tortor posuere ac ut consequat semper viverra nam. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo.\n\nSit amet commodo nulla facilisi nullam vehicula. Quis auctor elit sed vulputate mi sit. Donec massa sapien faucibus et molestie. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Pellentesque eu tincidunt tortor aliquam nulla. Potenti nullam ac tortor vitae purus. Integer malesuada nunc vel risus commodo viverra maecenas. Felis donec et odio pellentesque diam volutpat commodo sed. Vel quam elementum pulvinar etiam non. Sed arcu non odio euismod lacinia at quis risus. Id semper risus in hendrerit gravida rutrum quisque non tellus. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Arcu bibendum at varius vel.',
    Slug: 'letraset-une-société-de-lettrage-française',
    published_at: '2021-04-13T13:50:23.140Z',
    id: '3',
    categories: [
      {
        Name: 'Tech',
        id: '1',
      },
    ],
    Thumbnail: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_182_1200x500_7d5a4c0cd9.jpg',
          hash: 'large_182_1200x500_7d5a4c0cd9',
          mime: 'image/jpeg',
          name: 'large_182-1200x500.jpg',
          path: null,
          size: 67.85,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_182_1200x500_7d5a4c0cd9.jpg',
          hash: 'small_182_1200x500_7d5a4c0cd9',
          mime: 'image/jpeg',
          name: 'small_182-1200x500.jpg',
          path: null,
          size: 17.61,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_182_1200x500_7d5a4c0cd9.jpg',
          hash: 'medium_182_1200x500_7d5a4c0cd9',
          mime: 'image/jpeg',
          name: 'medium_182-1200x500.jpg',
          path: null,
          size: 39.38,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_182_1200x500_7d5a4c0cd9.jpg',
          hash: 'thumbnail_182_1200x500_7d5a4c0cd9',
          mime: 'image/jpeg',
          name: 'thumbnail_182-1200x500.jpg',
          path: null,
          size: 5.19,
          width: 245,
          height: 102,
        },
      },
    },
    author: {
      Name: 'Toni Hutter',
      email: 'hutter.toni@gmail.com',
      Image: {
        formats: {
          thumbnail: {
            ext: '.jpg',
            url: '/uploads/thumbnail_642_200x200_779ad53fd9.jpg',
            hash: 'thumbnail_642_200x200_779ad53fd9',
            mime: 'image/jpeg',
            name: 'thumbnail_642-200x200.jpg',
            path: null,
            size: 5.35,
            width: 156,
            height: 156,
          },
        },
      },
    },
  },
  {
    Title: 'Headless CMS',
    Description: 'An article about Headless CMS',
    Content:
      'Bavaria ipsum dolor sit amet owe vui huift vui Bussal, Schmankal measi Ohrwaschl des is a gmahde Wiesn i hab an und sei. Semmlkneedl wui i sog ja nix, i red ja bloß schaugn Foidweg baddscher measi glacht im Beidl imma ja, wo samma denn. Oa zwoa oa hinter’m Berg san a no Leit i moan scho aa zua i hab an, umananda. Wurschtsolod hoid Schneid da dringma aweng, oa Engelgwand Biagadn singd. Trachtnhuat am acht’n Tag schuf Gott des Bia Radler, von! Ham hawadere midananda eana Stubn sog i mim Radl foahn Sauakraud des is schee etza. Nix Gwiass woass ma ned Watschnbaam a so a Schmarn eana gor hogg ma uns zamm. Edlweiss oa Weißwiaschd hob i an Suri fias Baamwach des is hoid aso, back mas mim Radl foahn gfreit mi naa! Des muas ma hoid kenna Haferl Radler aba gwiss a fescha Bua, no. Do gschmeidig singd Maßkruag scheans.',
    Slug: 'headless-cms',
    published_at: '2021-02-20T14:56:37.868Z',
    id: '1',
    categories: [
      {
        Name: 'Tech',
        id: '1',
      },
      {
        Name: 'Nature',
        id: '3',
      },
    ],
    Thumbnail: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_407_1200x500_f12c3f8802.jpg',
          hash: 'large_407_1200x500_f12c3f8802',
          mime: 'image/jpeg',
          name: 'large_407-1200x500.jpg',
          path: null,
          size: 41.24,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_407_1200x500_f12c3f8802.jpg',
          hash: 'small_407_1200x500_f12c3f8802',
          mime: 'image/jpeg',
          name: 'small_407-1200x500.jpg',
          path: null,
          size: 14.47,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_407_1200x500_f12c3f8802.jpg',
          hash: 'medium_407_1200x500_f12c3f8802',
          mime: 'image/jpeg',
          name: 'medium_407-1200x500.jpg',
          path: null,
          size: 27.19,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_407_1200x500_f12c3f8802.jpg',
          hash: 'thumbnail_407_1200x500_f12c3f8802',
          mime: 'image/jpeg',
          name: 'thumbnail_407-1200x500.jpg',
          path: null,
          size: 5.17,
          width: 245,
          height: 102,
        },
      },
    },
    author: {
      Name: 'Toni Hutter',
      email: 'hutter.toni@gmail.com',
      Image: {
        formats: {
          thumbnail: {
            ext: '.jpg',
            url: '/uploads/thumbnail_642_200x200_779ad53fd9.jpg',
            hash: 'thumbnail_642_200x200_779ad53fd9',
            mime: 'image/jpeg',
            name: 'thumbnail_642-200x200.jpg',
            path: null,
            size: 5.35,
            width: 156,
            height: 156,
          },
        },
      },
    },
  },
  {
    Title: 'Lorem ipsum began as scrambled',
    Description:
      "Lorem ipsum began as scrambled, nonsensical Latin derived from Cicero's 1st-century BC text De Finibus Bonorum et Malorum.",
    Content:
      'At augue eget arcu dictum varius duis at consectetur lorem. Ultrices dui sapien eget mi proin sed. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Erat nam at lectus urna duis convallis convallis. Interdum velit laoreet id donec ultrices. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Aenean euismod elementum nisi quis eleifend. Auctor elit sed vulputate mi sit amet mauris. Mollis nunc sed id semper risus in. Praesent tristique magna sit amet purus gravida quis blandit. Ipsum suspendisse ultrices gravida dictum fusce. Mus mauris vitae ultricies leo integer. Fames ac turpis egestas integer eget aliquet nibh. Placerat vestibulum lectus mauris ultrices. Aliquet bibendum enim facilisis gravida neque convallis a. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Odio facilisis mauris sit amet massa vitae tortor. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Morbi leo urna molestie at elementum eu facilisis.\n\nTurpis nunc eget lorem dolor sed viverra ipsum nunc. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Est ultricies integer quis auctor elit sed. Elementum nisi quis eleifend quam. Tellus in hac habitasse platea. Consectetur a erat nam at lectus. Nunc consequat interdum varius sit amet. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Sit amet consectetur adipiscing elit pellentesque. Enim praesent elementum facilisis leo vel. Amet consectetur adipiscing elit ut aliquam. Viverra justo nec ultrices dui sapien eget mi proin. Gravida in fermentum et sollicitudin ac orci phasellus. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Nunc id cursus metus aliquam eleifend. Sit amet mattis vulputate enim nulla aliquet. Senectus et netus et malesuada fames ac turpis. Diam in arcu cursus euismod quis viverra nibh.',
    Slug: 'lorem-ipsum-began-as-scrambled',
    published_at: '2021-04-13T13:59:38.294Z',
    id: '5',
    categories: [
      {
        Name: 'Nature',
        id: '3',
      },
    ],
    Thumbnail: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_165_1200x500_dfda9cd6e3.jpg',
          hash: 'large_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'large_165-1200x500.jpg',
          path: null,
          size: 49.8,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_165_1200x500_dfda9cd6e3.jpg',
          hash: 'small_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'small_165-1200x500.jpg',
          path: null,
          size: 13.12,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_165_1200x500_dfda9cd6e3.jpg',
          hash: 'medium_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'medium_165-1200x500.jpg',
          path: null,
          size: 29.23,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_165_1200x500_dfda9cd6e3.jpg',
          hash: 'thumbnail_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'thumbnail_165-1200x500.jpg',
          path: null,
          size: 3.93,
          width: 245,
          height: 102,
        },
      },
    },
    author: {
      Name: 'Rene Descartes',
      email: 'rene.descartes.@mail.com',
      Image: {
        formats: {
          thumbnail: {
            ext: '.jpg',
            url: '/uploads/thumbnail_30_200x200_a4c5a5a868.jpg',
            hash: 'thumbnail_30_200x200_a4c5a5a868',
            mime: 'image/jpeg',
            name: 'thumbnail_30-200x200.jpg',
            path: null,
            size: 5.17,
            width: 156,
            height: 156,
          },
        },
      },
    },
  },
  {
    Title: 'From its medieval origins to the digital era',
    Description:
      'From its medieval origins to the digital era, learn everything there is to know about the ubiquitous lorem ipsum passage.',
    Content:
      'Donec pretium vulputate sapien nec. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Lectus sit amet est placerat in. Sed enim ut sem viverra aliquet. Scelerisque purus semper eget duis at tellus at urna. Est lorem ipsum dolor sit. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Pulvinar mattis nunc sed blandit libero volutpat sed. Urna neque viverra justo nec ultrices. Nisi lacus sed viverra tellus in hac habitasse platea. Feugiat in fermentum posuere urna nec tincidunt. Congue quisque egestas diam in arcu cursus euismod quis viverra. Sem integer vitae justo eget magna fermentum.\n\nSit amet massa vitae tortor. Pharetra convallis posuere morbi leo urna. Massa enim nec dui nunc mattis enim. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Sed pulvinar proin gravida hendrerit. Dolor purus non enim praesent elementum facilisis leo vel. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Cursus risus at ultrices mi tempus imperdiet nulla. Viverra nibh cras pulvinar mattis nunc sed. Hac habitasse platea dictumst quisque sagittis purus sit. Arcu non sodales neque sodales ut etiam.\n\nNec ultrices dui sapien eget mi. Viverra accumsan in nisl nisi. Ac felis donec et odio. Suspendisse in est ante in nibh. Porta non pulvinar neque laoreet. At imperdiet dui accumsan sit amet nulla. Ornare aenean euismod elementum nisi. Sed viverra tellus in hac. Nunc eget lorem dolor sed viverra ipsum. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Dolor sit amet consectetur adipiscing elit. Lacus sed turpis tincidunt id aliquet risus.',
    Slug: 'from-its-medieval-origins-to-the-digital-era',
    published_at: '2021-04-13T13:52:23.790Z',
    id: '4',
    categories: [
      {
        Name: 'Tech',
        id: '1',
      },
    ],
    Thumbnail: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_882_1200x500_3de98a9d2c.jpg',
          hash: 'large_882_1200x500_3de98a9d2c',
          mime: 'image/jpeg',
          name: 'large_882-1200x500.jpg',
          path: null,
          size: 60.08,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_882_1200x500_3de98a9d2c.jpg',
          hash: 'small_882_1200x500_3de98a9d2c',
          mime: 'image/jpeg',
          name: 'small_882-1200x500.jpg',
          path: null,
          size: 17.18,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_882_1200x500_3de98a9d2c.jpg',
          hash: 'medium_882_1200x500_3de98a9d2c',
          mime: 'image/jpeg',
          name: 'medium_882-1200x500.jpg',
          path: null,
          size: 36.22,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_882_1200x500_3de98a9d2c.jpg',
          hash: 'thumbnail_882_1200x500_3de98a9d2c',
          mime: 'image/jpeg',
          name: 'thumbnail_882-1200x500.jpg',
          path: null,
          size: 5.68,
          width: 245,
          height: 102,
        },
      },
    },
    author: {
      Name: 'Toni Hutter',
      email: 'hutter.toni@gmail.com',
      Image: {
        formats: {
          thumbnail: {
            ext: '.jpg',
            url: '/uploads/thumbnail_642_200x200_779ad53fd9.jpg',
            hash: 'thumbnail_642_200x200_779ad53fd9',
            mime: 'image/jpeg',
            name: 'thumbnail_642-200x200.jpg',
            path: null,
            size: 5.35,
            width: 156,
            height: 156,
          },
        },
      },
    },
  },
  {
    Title: 'From its medieval origins to the digital era.',
    Description:
      'From its medieval origins to the digital era, learn everything there is to know about the ubiquitous lorem ipsum passage.',
    Content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Augue lacus viverra vitae congue eu consequat ac. Fringilla ut morbi tincidunt augue interdum velit euismod in. Nulla facilisi nullam vehicula ipsum a arcu. Vivamus arcu felis bibendum ut tristique et egestas. Turpis egestas sed tempus urna et pharetra. Sit amet consectetur adipiscing elit. Eget lorem dolor sed viverra ipsum nunc. Aliquet enim tortor at auctor urna nunc id cursus. Adipiscing at in tellus integer feugiat scelerisque varius. Congue eu consequat ac felis donec et odio. Quis lectus nulla at volutpat diam ut venenatis tellus in. Suspendisse faucibus interdum posuere lorem ipsum dolor. Consectetur adipiscing elit ut aliquam purus sit amet luctus.\n\nA pellentesque sit amet porttitor eget dolor morbi non arcu. Commodo quis imperdiet massa tincidunt nunc pulvinar. Enim ut tellus elementum sagittis. Commodo ullamcorper a lacus vestibulum sed arcu. Enim diam vulputate ut pharetra sit amet. Pellentesque nec nam aliquam sem. Semper eget duis at tellus. Tristique sollicitudin nibh sit amet. Felis imperdiet proin fermentum leo. Viverra tellus in hac habitasse. Vitae auctor eu augue ut lectus arcu. Odio ut sem nulla pharetra diam sit amet. Sit amet risus nullam eget. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Nulla porttitor massa id neque.',
    Slug: 'from-its-medieval-origins-to-the-digital-era.',
    published_at: '2021-04-12T15:03:42.276Z',
    id: '2',
    categories: [
      {
        Name: 'Tech',
        id: '1',
      },
      {
        Name: 'News',
        id: '2',
      },
    ],
    Thumbnail: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_1043_1200x500_689358d5d2.jpg',
          hash: 'large_1043_1200x500_689358d5d2',
          mime: 'image/jpeg',
          name: 'large_1043-1200x500.jpg',
          path: null,
          size: 135.04,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_1043_1200x500_689358d5d2.jpg',
          hash: 'small_1043_1200x500_689358d5d2',
          mime: 'image/jpeg',
          name: 'small_1043-1200x500.jpg',
          path: null,
          size: 33.14,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_1043_1200x500_689358d5d2.jpg',
          hash: 'medium_1043_1200x500_689358d5d2',
          mime: 'image/jpeg',
          name: 'medium_1043-1200x500.jpg',
          path: null,
          size: 78.06,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_1043_1200x500_689358d5d2.jpg',
          hash: 'thumbnail_1043_1200x500_689358d5d2',
          mime: 'image/jpeg',
          name: 'thumbnail_1043-1200x500.jpg',
          path: null,
          size: 8.36,
          width: 245,
          height: 102,
        },
      },
    },
    author: {
      Name: 'Toni Hutter',
      email: 'hutter.toni@gmail.com',
      Image: {
        formats: {
          thumbnail: {
            ext: '.jpg',
            url: '/uploads/thumbnail_642_200x200_779ad53fd9.jpg',
            hash: 'thumbnail_642_200x200_779ad53fd9',
            mime: 'image/jpeg',
            name: 'thumbnail_642-200x200.jpg',
            path: null,
            size: 5.35,
            width: 156,
            height: 156,
          },
        },
      },
    },
  },
];
