export const ROUTES = {
  ROOT: {
    DRAWER: 'ROOT_DRAWER',
  },
  DRAWER: {
    HOME: 'ROOT_DRAWER_HOME',
    PRODUCTS: 'ROOT_DRAWER_PRODUCTS',
  },
  NESTEDSTACK: {
    HOME: 'DRAWER_HOME',
    PRODUCTS: 'DRAWER_PRODUCTS',
    DETAILS: 'NESTEDSTACK_DETAILS',
  },
};

export const INITIAL_NESTED_ROUTE = {
  ROOT_DRAWER_HOME: ROUTES.NESTEDSTACK.HOME,
  ROOT_DRAWER_PRODUCTS: ROUTES.NESTEDSTACK.PRODUCTS,
};

export const STRAPI_BASE_URL = 'http://localhost:1337';
