export const products = [
  {
    id: '1',
    Name: 'Mütze',
    Description:
      'Bavaria ipsum dolor sit amet mi scheans i mog di fei kummd hod! Auf’d Schellnsau barfuaßat Landla hogg di hera und, sammawiedaguad hallelujah sog i, luja. Foidweg Deandlgwand Hemad Maderln sei, kummd dahoam Graudwiggal a so a Schmarn? A Prosit der Gmiadlichkeit Zidern Habedehre Hemad griasd eich midnand Hemad boarischer Maßkruag iabaroi. I daad Gaudi und Trachtnhuat resch auf der Oim, da gibt’s koa Sünd vui Deandlgwand anbandeln hoam is. Griasnoggalsubbm eam nackata, ned woar! Oans, zwoa, gsuffa koa Weiznglasl aasgem Musi gscheid. Weiznglasl a bissal wos gehd ollaweil Mamalad sodala umananda a ganze, auffi. A bissal wos gehd ollaweil wolln middn wui, an a geh a so a Schmarn Vergeltsgott auf’d Schellnsau auf gehds beim Schichtl woaß: In da gfreit mi san di an schüds nei da hob i an Suri nix, i.',
    Slug: 'muetze',
    Gallery: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_165_1200x500_dfda9cd6e3.jpg',
          hash: 'large_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'large_165-1200x500.jpg',
          path: null,
          size: 49.8,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_165_1200x500_dfda9cd6e3.jpg',
          hash: 'small_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'small_165-1200x500.jpg',
          path: null,
          size: 13.12,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_165_1200x500_dfda9cd6e3.jpg',
          hash: 'medium_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'medium_165-1200x500.jpg',
          path: null,
          size: 29.23,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_165_1200x500_dfda9cd6e3.jpg',
          hash: 'thumbnail_165_1200x500_dfda9cd6e3',
          mime: 'image/jpeg',
          name: 'thumbnail_165-1200x500.jpg',
          path: null,
          size: 3.93,
          width: 245,
          height: 102,
        },
      },
    },
    Price: 12.99,
  },
  {
    id: '2',
    Name: 'Porttitor lacus ',
    Description:
      'Porttitor lacus luctus accumsan tortor posuere ac. Varius morbi enim nunc faucibus a pellentesque sit. Orci a scelerisque purus semper eget duis. Laoreet sit amet cursus sit amet dictum sit amet. Augue interdum velit euismod in pellentesque massa placerat duis. A lacus vestibulum sed arcu non. Lorem mollis aliquam ut porttitor leo a. Ornare aenean euismod elementum nisi quis. Vitae purus faucibus ornare suspendisse sed nisi. Arcu ac tortor dignissim convallis aenean et tortor at risus. Risus in hendrerit gravida rutrum quisque non tellus orci. Mauris sit amet massa vitae tortor.',
    Slug: 'porttitor-lacus ',
    Gallery: {
      formats: {
        large: {
          ext: '.jpg',
          url: '/uploads/large_162_1200x500_d3c5c0d451.jpg',
          hash: 'large_162_1200x500_d3c5c0d451',
          mime: 'image/jpeg',
          name: 'large_162-1200x500.jpg',
          path: null,
          size: 97.66,
          width: 1000,
          height: 417,
        },
        small: {
          ext: '.jpg',
          url: '/uploads/small_162_1200x500_d3c5c0d451.jpg',
          hash: 'small_162_1200x500_d3c5c0d451',
          mime: 'image/jpeg',
          name: 'small_162-1200x500.jpg',
          path: null,
          size: 24.88,
          width: 500,
          height: 208,
        },
        medium: {
          ext: '.jpg',
          url: '/uploads/medium_162_1200x500_d3c5c0d451.jpg',
          hash: 'medium_162_1200x500_d3c5c0d451',
          mime: 'image/jpeg',
          name: 'medium_162-1200x500.jpg',
          path: null,
          size: 57.43,
          width: 750,
          height: 313,
        },
        thumbnail: {
          ext: '.jpg',
          url: '/uploads/thumbnail_162_1200x500_d3c5c0d451.jpg',
          hash: 'thumbnail_162_1200x500_d3c5c0d451',
          mime: 'image/jpeg',
          name: 'thumbnail_162-1200x500.jpg',
          path: null,
          size: 6.28,
          width: 245,
          height: 102,
        },
      },
    },
    Price: 500,
  },
];
